# Generated by Django 5.2.15 on 2026-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курси"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенти",
            },
        ),
    ]
