# Generated by Django 5.2.15 on 2026-06-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_transfer_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='telegram_chat_id',
        ),
    ]
