# Generated by Django 5.2.15 on 2026-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Користувач", "verbose_name_plural": "Користувачі"},
        ),
    ]
