# Generated by Django 5.2.15 on 2026-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Власник'), ('manager', 'Менеджер'), ('teacher', 'Викладач'), ('parent', 'Батько/мати'), ('student', 'Студент')], default='student', max_length=20),
        ),
    ]
