# Generated by Django 5.2.15 on 2026-08-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_roles_and_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Власник'), ('manager', 'Менеджер'), ('teacher', 'Викладач'), ('parent', 'Батько/мати'), ('student', 'Студент')], default='student', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
