# Generated by Django 5.2.15 on 2026-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('filename', models.CharField(max_length=255, verbose_name='Файл')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Розмір (байт)')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Тривалість (с)')),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('failed', 'Помилка')], db_index=True, max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Перевірено (легка)')),
                ('verified_ok', models.BooleanField(null=True, verbose_name='Легка перевірка успішна')),
                ('full_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Перевірено (повна)')),
                ('full_verified_ok', models.BooleanField(null=True, verbose_name='Повна перевірка успішна')),
            ],
            options={
                'verbose_name': 'Резервна копія',
                'verbose_name_plural': 'Резервні копії',
                'ordering': ['-created_at'],
            },
        ),
    ]
