# Generated by Django 5.2.15 on 2026-06-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
