# Generated by Django 5.2.15 on 2026-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклад'},
        ),
    ]
