# Generated by Django 5.2.15 on 2026-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleaccount',
            options={'verbose_name': 'Google акаунт', 'verbose_name_plural': 'Google акаунти'},
        ),
    ]
