# Generated by Django 5.2.15 on 2026-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "ordering": ["-sent_at"],
                "verbose_name": "Лог сповіщень",
                "verbose_name_plural": "Логи сповіщень",
            },
        ),
    ]
