# Generated by Django 5.2.15 on 2026-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Лог сповіщення', 'verbose_name_plural': 'Логи сповіщень'},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('payment_reminder', 'Нагадування про оплату'), ('welcome', 'Вітання нового користувача'), ('schedule_change', 'Зміна розкладу'), ('class_reminder', 'Нагадування про заняття'), ('broadcast', 'Розсилка')], db_index=True, default='payment_reminder', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_be328b_idx'),
        ),
    ]
