# Generated by Django 5.2.15 on 2026-08-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('payment_reminder', 'Нагадування про оплату'), ('welcome', 'Вітання нового користувача'), ('schedule_change', 'Зміна розкладу'), ('class_reminder', 'Нагадування про заняття'), ('broadcast', 'Розсилка')], db_index=True, default='payment_reminder', max_length=30, verbose_name='Вид сповіщення'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата надсилання'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Надіслано'), ('failed', 'Помилка')], default='sent', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип'),
        ),
    ]
